name: CI

env:
  MAIN_BRANCH: main

on:
  push:
    branches:
      - $MAIN_BRANCH
      - '!gh-pages'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rust-toolchain (Stable)
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Install mdBook
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Lint Markdown files
        run: npm run lint

      - name: Build documentation
        run: npm run build

      - name: Deploy documentation
        if: github.event_name != 'pull_request' && github.event.ref == 'refs/heads/$MAIN_BRANCH'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
