name: CI

#env:
#  MAIN_BRANCH: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      # Failing with:
      # Action failed with error Error: ENOENT: no such file or directory, rename
      #   '/home/runner/tmp/target/x86_64-unknown-linux-gnu/release/mdbook-katex'
      #   -> '/home/runner/toolbin/mdbook-katex'
      #
      # - name: Setup mdbook-katex
      #   uses: magicgh/mdbook-katex-action@v1.1.0
      #   with:
      #     version: 'latest'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Lint Markdown files
        run: npm run lint

      - name: Build documentation
        run: npm run build

      - name: Deploy documentation
        if: github.event_name != 'pull_request' && github.event.ref == 'refs/heads/main'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
